export const AdminRoutes = '/admin' 
export const LogRoutes = '/log' 
export const RegRoutes = '/reg' 
export const PasswordErrorRoutes = '/passerror'
export const AgencyRoutes = '/'    
export const AppsRoutes = '/apps'  
